package MethodsExercises;

import java.util.Scanner;

public class _09_method9 {
    /*
  Create a method named findTheDifference.
     must consist of two Strings.
     The return data type must be char.
     Name these two strings s and t and enter values made up of lowercase letters.
     String t is generated by random scrambling strings String s and
     it then adds another letter at a random location. Find the letter appended to String t.
     (Print the element that is in String s but not in String t .)

     eg:
     Entry:
     s = "abcde"
     t = "abcd"
     Output:
     e

     Explanation:
     The letter 'e' has been added.

     s = "qawer"
     t = "rewq"
     Output:
     a
     Explanation:
     The letter 'a' has been added.
     */

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        System.out.print("s : ");
        String s = scanner.nextLine();
        s = s.toLowerCase();

        System.out.print("t : ");
        String t = scanner.nextLine();
        t = t.toLowerCase();

        System.out.println(findTheDifference(s,t));




    }
    public static char findTheDifference(String s, String t){

        char[] arrS = s.toCharArray();
        char farkli = ' ';

        for (int i = 0; i < arrS.length ; i++) {
            if (t.indexOf(arrS[i]) < 0){
                farkli=arrS[i];
            }
        }
        return farkli;
    }
}
